// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psxqfwlsehixrqlbqotb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzeHFmd2xzZWhpeHJxbGJxb3RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNTIyODIsImV4cCI6MjA2NzYyODI4Mn0.QkZfcAV6ocIBLk9-S3DylhgSbyaqD8cAr1oLDv9c0AM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});